### PR TITLE
Functions

### PR DESCRIPTION
**Pull request by RidwanAdebosin**
I am rounding up with the contents on Function but check these contents for addition and corrections.

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
@Oluwasetemi @Olubebe @Rolalove please review. Thanks @RidwanAdebosin

**Comment by RidwanAdebosin** [comment]
Sure @Rolalove 
I will work on your recommendation.

**Comment by Olubebe** [comment]
Great work @RidwanAdebosin 👏🏿 
But at the beginning of the note you used green background colors on the code it contracts the color of the code I can't really read it

**Comment by RidwanAdebosin** [comment]
Thank you, @Olubebe .
I am going to remove all the extra colors in the slides.

**Comment by Oluwasetemi** [comment]
@RidwanAdebosin, the green color is good for learning but the text inside it in dark mode is what needs to be brighter. Have the same look and feel for all the sides does not encourage another challenge/new vibe of a new chapter. If you can find a good blend for the headers in darkmode, the green and white shade need to invert like making the green lightness reduce while the white can be more bright. the code background seems interesting in light mode but in darkmode it overshadows and greenness is everywhere. 
Another thing is please add something on apply and bind since they are closely related to call. But you did a great work in the content.

**Comment by RidwanAdebosin** [comment]
@Oluwasetemi I am not done with the apply and bind content and also concerning the header color, I can work on the blend so that it can be better when the window is in dark mode, but other contents ain't having the background which is going to make the contents from my end looks odd. 

So, it's either we designed all header with a background color or we don't design any at all.

**Comment by RidwanAdebosin** [comment]
> > @Oluwasetemi I am not done with the apply and bind content and also concerning the header color, I can work on the blend so that it can be better when the window is in dark mode, but other contents ain't having the background which is going to make the contents from my end looks odd.
> > So, it's either we designed all header with a background color or we don't design any at all.
> 
> It's okay, we can have a todo to implement a good customizable header or feedback component with tip/info/success/danger like in the class tutorial. Until then we can even it out to look the same way. Thanks

Noted.

**Comment by RidwanAdebosin** [comment]
Sequel to the reviews, I have fixed it and completed the content on func.call(). 
I have started writing on func.apply()

**Comment by Oluwasetemi** [comment]
> Sequel to the reviews, I have fixed it and completed the content on func.call(). I have started writing on func.apply()

thanks for the good work. I cannot wait to merge the PR. >>>> 👌

**Comment by RidwanAdebosin** [comment]
> > Sequel to the reviews, I have fixed it and completed the content on func.call(). I have started writing on func.apply()
> 
> thanks for the good work. I cannot wait to merge the PR. >>>> 👌

I am done with it, please check now.

**Comment by Oluwasetemi** [comment]
@RidwanAdebosin there is a conflict that need to be resolved before we can merge

**Comment by RidwanAdebosin** [comment]
> @RidwanAdebosin there is a conflict that need to be resolved before we can merge

I will check it.

**Review by Oluwasetemi — APPROVED** [review]

**Pull request merged**
