### PR TITLE
documentation-resource-loading

### PR DESCRIPTION
**Pull request by Racheal-cloud**
I worked on the documentation resource loading and completed the notes on the page and script. I would complete the resource loading note before the end of the week. Kindly review.

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
this is a test comment

**Comment by Oluwasetemi** [comment]
sorry this is a test comment 2

**Comment by Oluwasetemi** [comment]
sorry this is a test comment 2

**Comment by Oluwasetemi** [comment]
This is a new comment

**Comment by Oluwasetemi** [comment]
This is a new comment 🤩

**Comment by Oluwasetemi** [comment]
any update on this @Racheal-cloud?

**Comment by Racheal-cloud** [comment]
Note updated

> any update on this @Racheal-cloud?

Notes updated. Kindly review.

**Comment by Oluwasetemi** [comment]
Noted

**Review by Oluwasetemi — APPROVED** [review]

**Comment by Oluwasetemi** [comment]
@Racheal-cloud it looks good. thanks for the effort

**Review by Oluwasetemi — CHANGES_REQUESTED** [review]
@Racheal-cloud can you pull the latest main into your branch. I made some UI changes.

**Pull request merged**
