### PR TITLE
Added error-handling chapter

### PR DESCRIPTION
**Pull request by kolapowariz**
Added Error handling chapter which consists Error handling `try...catch` and custom errors

Closes issue #13 

image

### CODE REVIEW

**Review by Oluwasetemi — APPROVED** [review]

**Review by RidwanAdebosin — APPROVED** [review]

**Comment by Rolalove** [comment]
Screenshot 2024-10-08 182912
  
You can bypass this first paragraph from being faint by using a div tag, also instead of the purple bg used to highlight important point you can use a text-red.

# Error handling, "try..catch"
<div><div>

<v-clicks>

Programming errors can occur due to various reasons. The `try...catch` syntax allows us to handle these errors gracefully instead of abruptly stopping the script. `try...catch` only works for runtime errors.

**Review by Rolalove — COMMENTED** [review]
The content is good,  the only issue i can sight, i made a comment about it.
Once that is fixed, we are good on Error handling.

**Comment by kolapowariz** [comment]
> Screenshot 2024-10-08 182912
> 
> You can bypass this first paragraph from being faint by using a div tag, also instead of the purple bg used to highlight important point you can use a text-red.
> 
> # Error handling, "try..catch"
> Programming errors can occur due to various reasons. The `try...catch` syntax allows us to handle these errors gracefully instead of abruptly stopping the script. `try...catch` only works for runtime errors.

That's noted

**Comment by Rolalove** [comment]
> > Screenshot 2024-10-08 182912
> > You can bypass this first paragraph from being faint by using a div tag, also instead of the purple bg used to highlight important point you can use a text-red.
> > # Error handling, "try..catch"
> > Programming errors can occur due to various reasons. The `try...catch` syntax allows us to handle these errors gracefully instead of abruptly stopping the script. `try...catch` only works for runtime errors.
> 
> That's noted

Amazing work done @kolapowariz

**Review by Rolalove — APPROVED** [review]

**Pull request merged**
